services:
  - type: web
    name: biopack-simulador
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ADMIN_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
